apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
        - pause: { duration: 120s }
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/bvrazvan/ci_cd_lab@sha256:1b552fda1b345bffcf90de94900adc073558cca8598b65531cf42c35bc3394af
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

